#! /bin/sh
# Running `autom4te' as if it were installed.

. ./atconfig

# Be sure to use the non installed Perl modules.
# We need no special protection for the subtools (e.g., autoheader runs
# autoconf which runs autom4te) because by themselves, they try to use
# subtools from the same directory (i.e., foo/autoheader will run
# foo/autoconf etc.).
autom4te_perllibdir=$top_srcdir/lib
export autom4te_perllibdir

AUTOM4TE_CFG=$top_builddir/lib/autom4te.cfg
export AUTOM4TE_CFG

# We might need files from build (frozen files), in addition of src files.
exec ../bin/autom4te -I ../lib -I $top_srcdir/lib ${1+"$@"}
