#! /bin/sh
# Running `autoheader' as if it were installed.

. ./atconfig

# Be sure to use the non installed Perl modules.
# We need no special protection for the subtools (e.g., autoheader runs
# autoconf which runs autom4te) because by themselves, they try to use
# subtools from the same directory (i.e., foo/autoheader will run
# foo/autoconf etc.).
autom4te_perllibdir=$top_srcdir/lib
export autom4te_perllibdir

exec ../bin/autoheader --autoconf-dir ../lib ${1+"$@"}
